name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: .

      - name: List files to verify
        run: ls -la

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm start