name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # First, we need to get the ID of the CI workflow that triggered this CD workflow
      - name: Get CI Workflow Run ID
        run: echo "CI_RUN_ID=${{ github.event.workflow_run.id }}" >> $GITHUB_ENV

      # Then we use that ID to download the exact artifact
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app-package
          path: ./deployment-package
          run-id: ${{ env.CI_RUN_ID }}  # This is the crucial fix!

      - name: Unzip and Prepare Artifact
        run: |
          cd ./deployment-package
          unzip -o my-app.zip -d ../live-app
          cd ../live-app

      - name: Install Dependencies
        run: npm ci --production
        working-directory: ./live-app

      - name: Set Environment Variables
        run: |
          echo "APP_ENV=production" >> $GITHUB_ENV
          echo "PORT=3000" >> $GITHUB_ENV
        working-directory: ./live-app

      - name: Verify Deployment Files
        run: ls -la
        working-directory: ./live-app

      - name: Start Application
        run: npm start
        working-directory: ./live-app
        env:
          PORT: ${{ env.PORT }}
          APP_ENV: ${{ env.APP_ENV }}