name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Download using GitHub CLI (no installation needed)
      - name: Download artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run download ${{ github.event.workflow_run.id }} --artifact node-app-artifact --dir .
          
      - name: List downloaded files
        run: ls -la

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm start