name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      # Configure Git with the PAT for authentication
      - name: Setup Git authentication
        run: |
          git config --global url."https://api:${{ secrets.RUNNER_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"
          
      # Download the artifact using the download action with the PAT
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app-artifact
          path: .
          token: ${{ secrets.RUNNER_ACCESS_TOKEN }}
          
      - name: List files
        run: ls -la
        
      - name: Install dependencies
        run: npm install
        
      - name: Start server
        run: npm start