name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Download artifact using PAT token
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app-build
          path: ${{ github.workspace }}/build
          token: ${{ secrets.PAT_TOKEN }}

      - name: Verify downloaded files
        run: |
          echo "Downloaded files:"
          ls -la ${{ github.workspace }}/build/
          echo "Package.json content:"
          cat ${{ github.workspace }}/build/package.json

      - name: Install dependencies
        run: npm install
        working-directory: ${{ github.workspace }}/build

      - name: Start server
        run: npm start
        working-directory: ${{ github.workspace }}/build