name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Create build directory
        run: |
          mkdir -p ${{ github.workspace }}/build
          cp app.js package.json ${{ github.workspace }}/build/
          echo "Build contents:"
          ls -la ${{ github.workspace }}/build/

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app-build
          path: ${{ github.workspace }}/build